name: landsat-ml-cookbook
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - shapely<2.0.0
  - pandas
  - xarray-datatree
  - planetary-computer
  - pystac
  - pystac-client
  - odc-stac
  - ipykernel
  - hvplot
  - panel
  - geoviews<1.10
  - datashader
  - colorcet
  - intake
  - intake-xarray<0.7
  - xarray=2023.04
  - bokeh<3.0
  - dask
  - dask-ml
  - pandas
  - numpy
  - cartopy
  - rioxarray
  - rasterio
  - s3fs
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pyopenssl>22
  - adlfs
  - pip
  - pip:
      - sphinx-pythia-theme
      - stac_geoparquet
      - dask_geopandas
      - jupyter_bokeh
      - pygeos
