name: landsat-ml-cookbook
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - shapely<2.0.0
  - pandas
  - xarray-datatree
  - planetary-computer
  - pystac
  - pystac-client
  - odc-stac
  - ipykernel
  - hvplot
  - panel<1.4.0
  - geoviews
  - datashader
  - colorcet
  - intake>2.0.4
  - intake-xarray
  - xarray<2023.04
  - bokeh<3.4.0
  - dask
  - dask-ml
  - pandas
  - numpy
  - cartopy
  - rioxarray
  - rasterio
  - s3fs
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pyopenssl>22
  - adlfs
  # The balance of this environment file pins several libraries in order for
  # to satisfy dependencies for the sphinx-pythia-theme 2022.3.22 package.
  - sphinx==4.5.0
  - sphinxcontrib-applehelp<1.0.7 
  - sphinxcontrib-devhelp<1.0.5 
  - sphinxcontrib-htmlhelp<2.0.4 
  - sphinxcontrib-qthelp<1.0.6 
  - sphinxcontrib-serializinghtml<1.1.9
  - pydata-sphinx-theme<=0.8
  - jsonschema-with-format-nongpl<4.19.1
  - docutils==0.16
  - pip
  - pip:
      - sphinx-pythia-theme
      - stac_geoparquet
      - dask_geopandas
      - jupyter_bokeh
      - pygeos
